name: strudel
channels:
  - conda-forge
dependencies:
  - code-server>=4.0
  - git
  - jupyter-vscode-proxy
  - jupyter-server-proxy
  - nbgitpuller
  - gh-scoped-creds
  - pip
  - pip:
      - strudel-cli
      - git-credential-helpers
